[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#4B0082"  # Japanese indigo (紺色)
backgroundColor = "#FFFFFF"  # Pure white (白)
secondaryBackgroundColor = "#F5F5F5"  # Light grey (白鼠)
textColor = "#333333"  # Dark grey for text
font = "sans serif"
